name: Test

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v2

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 6

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 14
          cache: 'pnpm'

      - name: Install
        run: pnpm install

      - name: Build
        run: pnpm run build

      - name: Test
        run: pnpm run coverage
