name: Test

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  coverage:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
          cache: 'pnpm'

      - name: Setup Pnpm
        uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.24.x
          run_install: true

      - name: Install
        run: pnpm i

      - name: Build
        run: pnpm run build

      - name: Test
        run: pnpm run coverage
